### ISSUE TITLE
Update Kubelet Configurations - Control 3.2.11

### ISSUE THREAD

**Issue by akrohg-dcca** [mitre/eks-cis-node-baseline#6]
The control 3.2.11 tests that the kubelet server certificate rotation option is enabled, however the control currently looks in the wrong place within the kubelet configuration file. This results in this control Failing, even though we are following the benchmark.

The RotateKubeletServerCertificate option is actually located within the featureGates section of the kubelet config file.
Reference: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates

Snippet from latest CIS benchmark showing updated remediation step:
![image](https://github.com/mitre/eks-cis-node-baseline/assets/124793803/c439fbc5-9d0d-4c06-aad3-c097c51fa5dc)

NOTE: The second option of the CIS benchmark, modifying the service option, also seems out of date - there is no "--rotate-kubelet-server-certificate" option mentioned in any Kubernetes documentation, the similar relevant-looking option would be "--rotate-server-certificates".
Reference: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#options
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration
For our team, it would be good enough if we just fixed the first part to check the kubelet config file in the correct location per the latest CIS benchmark.

**Comment by akrohg-dcca** [comment]
I have a code change prepared to fix this issue, but do not currently have write access in this repository to create a Pull Request. Can I please be granted access to create a branch and Pull Request?

**Comment by Amndeep7** [comment]
Hi @akrohg-dcca, thanks for filing the issue and having a PR ready!  We do not usually allow members outside of the MITRE organization to directly make branches within our repos.  However, what you can do is create a fork of the repo, create your branch there, and then make a PR back to us upstream.  Once you've done so, please tag me directly so that I get a notification to take a look at it.

I'd also appreciate it if you could send me an email at amann@mitre.org - it's always nice to have opportunities to talk with users of the SAF.
